### YamlMime:ManagedReference
items:
- uid: Roulette.Models.SmtpSettings
  commentId: T:Roulette.Models.SmtpSettings
  id: SmtpSettings
  parent: Roulette.Models
  children:
  - Roulette.Models.SmtpSettings.EnableSsl
  - Roulette.Models.SmtpSettings.FromEmail
  - Roulette.Models.SmtpSettings.Host
  - Roulette.Models.SmtpSettings.Password
  - Roulette.Models.SmtpSettings.Port
  - Roulette.Models.SmtpSettings.Username
  langs:
  - csharp
  - vb
  name: SmtpSettings
  nameWithType: SmtpSettings
  fullName: Roulette.Models.SmtpSettings
  type: Class
  source:
    remote:
      path: Roulette/Models/SmtpSettings.cs
      branch: develop
      repo: https://github.com/Lanctole/Roulette.git
    id: SmtpSettings
    path: ../Roulette/Models/SmtpSettings.cs
    startLine: 5
  assemblies:
  - Roulette
  namespace: Roulette.Models
  summary: Настройки для конфигурации SMTP сервера для отправки электронной почты.
  example: []
  syntax:
    content: public class SmtpSettings
    content.vb: Public Class SmtpSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Roulette.Models.SmtpSettings.Host
  commentId: P:Roulette.Models.SmtpSettings.Host
  id: Host
  parent: Roulette.Models.SmtpSettings
  langs:
  - csharp
  - vb
  name: Host
  nameWithType: SmtpSettings.Host
  fullName: Roulette.Models.SmtpSettings.Host
  type: Property
  source:
    remote:
      path: Roulette/Models/SmtpSettings.cs
      branch: develop
      repo: https://github.com/Lanctole/Roulette.git
    id: Host
    path: ../Roulette/Models/SmtpSettings.cs
    startLine: 7
  assemblies:
  - Roulette
  namespace: Roulette.Models
  syntax:
    content: public string Host { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Host As String
  overload: Roulette.Models.SmtpSettings.Host*
- uid: Roulette.Models.SmtpSettings.Port
  commentId: P:Roulette.Models.SmtpSettings.Port
  id: Port
  parent: Roulette.Models.SmtpSettings
  langs:
  - csharp
  - vb
  name: Port
  nameWithType: SmtpSettings.Port
  fullName: Roulette.Models.SmtpSettings.Port
  type: Property
  source:
    remote:
      path: Roulette/Models/SmtpSettings.cs
      branch: develop
      repo: https://github.com/Lanctole/Roulette.git
    id: Port
    path: ../Roulette/Models/SmtpSettings.cs
    startLine: 8
  assemblies:
  - Roulette
  namespace: Roulette.Models
  syntax:
    content: public int Port { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Port As Integer
  overload: Roulette.Models.SmtpSettings.Port*
- uid: Roulette.Models.SmtpSettings.EnableSsl
  commentId: P:Roulette.Models.SmtpSettings.EnableSsl
  id: EnableSsl
  parent: Roulette.Models.SmtpSettings
  langs:
  - csharp
  - vb
  name: EnableSsl
  nameWithType: SmtpSettings.EnableSsl
  fullName: Roulette.Models.SmtpSettings.EnableSsl
  type: Property
  source:
    remote:
      path: Roulette/Models/SmtpSettings.cs
      branch: develop
      repo: https://github.com/Lanctole/Roulette.git
    id: EnableSsl
    path: ../Roulette/Models/SmtpSettings.cs
    startLine: 9
  assemblies:
  - Roulette
  namespace: Roulette.Models
  syntax:
    content: public bool EnableSsl { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property EnableSsl As Boolean
  overload: Roulette.Models.SmtpSettings.EnableSsl*
- uid: Roulette.Models.SmtpSettings.Username
  commentId: P:Roulette.Models.SmtpSettings.Username
  id: Username
  parent: Roulette.Models.SmtpSettings
  langs:
  - csharp
  - vb
  name: Username
  nameWithType: SmtpSettings.Username
  fullName: Roulette.Models.SmtpSettings.Username
  type: Property
  source:
    remote:
      path: Roulette/Models/SmtpSettings.cs
      branch: develop
      repo: https://github.com/Lanctole/Roulette.git
    id: Username
    path: ../Roulette/Models/SmtpSettings.cs
    startLine: 10
  assemblies:
  - Roulette
  namespace: Roulette.Models
  syntax:
    content: public string Username { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Username As String
  overload: Roulette.Models.SmtpSettings.Username*
- uid: Roulette.Models.SmtpSettings.Password
  commentId: P:Roulette.Models.SmtpSettings.Password
  id: Password
  parent: Roulette.Models.SmtpSettings
  langs:
  - csharp
  - vb
  name: Password
  nameWithType: SmtpSettings.Password
  fullName: Roulette.Models.SmtpSettings.Password
  type: Property
  source:
    remote:
      path: Roulette/Models/SmtpSettings.cs
      branch: develop
      repo: https://github.com/Lanctole/Roulette.git
    id: Password
    path: ../Roulette/Models/SmtpSettings.cs
    startLine: 11
  assemblies:
  - Roulette
  namespace: Roulette.Models
  syntax:
    content: public string Password { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Password As String
  overload: Roulette.Models.SmtpSettings.Password*
- uid: Roulette.Models.SmtpSettings.FromEmail
  commentId: P:Roulette.Models.SmtpSettings.FromEmail
  id: FromEmail
  parent: Roulette.Models.SmtpSettings
  langs:
  - csharp
  - vb
  name: FromEmail
  nameWithType: SmtpSettings.FromEmail
  fullName: Roulette.Models.SmtpSettings.FromEmail
  type: Property
  source:
    remote:
      path: Roulette/Models/SmtpSettings.cs
      branch: develop
      repo: https://github.com/Lanctole/Roulette.git
    id: FromEmail
    path: ../Roulette/Models/SmtpSettings.cs
    startLine: 12
  assemblies:
  - Roulette
  namespace: Roulette.Models
  syntax:
    content: public string FromEmail { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property FromEmail As String
  overload: Roulette.Models.SmtpSettings.FromEmail*
references:
- uid: Roulette.Models
  commentId: N:Roulette.Models
  href: Roulette.html
  name: Roulette.Models
  nameWithType: Roulette.Models
  fullName: Roulette.Models
  spec.csharp:
  - uid: Roulette
    name: Roulette
    href: Roulette.html
  - name: .
  - uid: Roulette.Models
    name: Models
    href: Roulette.Models.html
  spec.vb:
  - uid: Roulette
    name: Roulette
    href: Roulette.html
  - name: .
  - uid: Roulette.Models
    name: Models
    href: Roulette.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Roulette.Models.SmtpSettings.Host*
  commentId: Overload:Roulette.Models.SmtpSettings.Host
  href: Roulette.Models.SmtpSettings.html#Roulette_Models_SmtpSettings_Host
  name: Host
  nameWithType: SmtpSettings.Host
  fullName: Roulette.Models.SmtpSettings.Host
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Roulette.Models.SmtpSettings.Port*
  commentId: Overload:Roulette.Models.SmtpSettings.Port
  href: Roulette.Models.SmtpSettings.html#Roulette_Models_SmtpSettings_Port
  name: Port
  nameWithType: SmtpSettings.Port
  fullName: Roulette.Models.SmtpSettings.Port
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: Roulette.Models.SmtpSettings.EnableSsl*
  commentId: Overload:Roulette.Models.SmtpSettings.EnableSsl
  href: Roulette.Models.SmtpSettings.html#Roulette_Models_SmtpSettings_EnableSsl
  name: EnableSsl
  nameWithType: SmtpSettings.EnableSsl
  fullName: Roulette.Models.SmtpSettings.EnableSsl
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Roulette.Models.SmtpSettings.Username*
  commentId: Overload:Roulette.Models.SmtpSettings.Username
  href: Roulette.Models.SmtpSettings.html#Roulette_Models_SmtpSettings_Username
  name: Username
  nameWithType: SmtpSettings.Username
  fullName: Roulette.Models.SmtpSettings.Username
- uid: Roulette.Models.SmtpSettings.Password*
  commentId: Overload:Roulette.Models.SmtpSettings.Password
  href: Roulette.Models.SmtpSettings.html#Roulette_Models_SmtpSettings_Password
  name: Password
  nameWithType: SmtpSettings.Password
  fullName: Roulette.Models.SmtpSettings.Password
- uid: Roulette.Models.SmtpSettings.FromEmail*
  commentId: Overload:Roulette.Models.SmtpSettings.FromEmail
  href: Roulette.Models.SmtpSettings.html#Roulette_Models_SmtpSettings_FromEmail
  name: FromEmail
  nameWithType: SmtpSettings.FromEmail
  fullName: Roulette.Models.SmtpSettings.FromEmail
